USE ROLE ROLE_POC_ENGINEER;
USE WAREHOUSE WH_POC_XS;

CREATE OR REPLACE PROCEDURE DB_POC_HARMONIZED.SCH_COMMON_UTILS.SP_CATCHUP_PROCESSOR("MAX_ITERATIONS" NUMBER(38,0) DEFAULT 50, "DELAY_THRESHOLD_MINS" NUMBER(38,0) DEFAULT 15)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
DECLARE
    CURRENT_DELAY_MINS NUMBER := 0;
    ITERATIONS_NEEDED NUMBER := 0;
    CURRENT_ITERATION NUMBER := 0;
    PROC_RESULT STRING := '';
    TOTAL_RESULTS STRING := '';
    TASK_STATE STRING := '';
    TASK_NAME STRING := 'DB_POC_HARMONIZED.SCH_COMMON_UTILS.TASK_POC_LOAD';
    TASK_WAS_RUNNING BOOLEAN := FALSE;
    IS_EXECUTING NUMBER := 0;
    WAIT_COUNTER NUMBER := 0;

BEGIN
    SELECT
        COALESCE(MAX(LATEST_PROCESSING_DELAY_MINS), 0),
        COALESCE(MAX(CATCHUP_ITERATIONS_NEEDED), 0)
    INTO :CURRENT_DELAY_MINS, :ITERATIONS_NEEDED
    FROM DB_POC_HARMONIZED.SCH_COMMON_UTILS.VW_PIPELINE_DELAY_MONITOR
    LIMIT 1;

    IF (:CURRENT_DELAY_MINS < :DELAY_THRESHOLD_MINS) THEN
        RETURN 'No Catchup Needed - pipeline is current (delay: ' || :CURRENT_DELAY_MINS || ' mins)';
    END IF;

    IF (:ITERATIONS_NEEDED > :MAX_ITERATIONS) THEN
        ITERATIONS_NEEDED := :MAX_ITERATIONS;
    END IF;

    TOTAL_RESULTS := '== CATCHUP INITIATED ==' || CHR(10);
    TOTAL_RESULTS := :TOTAL_RESULTS || 'Initial Delay: ' || :CURRENT_DELAY_MINS || ' mins' || CHR(10);
    TOTAL_RESULTS := :TOTAL_RESULTS || 'Estimated Iterations: ' || :ITERATIONS_NEEDED || CHR(10) || CHR(10);

    TOTAL_RESULTS := :TOTAL_RESULTS || '== TASK CONTROL ==' || CHR(10);

    BEGIN
        EXECUTE IMMEDIATE 'SHOW TASKS LIKE ''TASK_POC_LOAD'' IN SCHEMA DB_POC_HARMONIZED.SCH_COMMON_UTILS';
        LET task_cursor CURSOR FOR
            SELECT "state" AS TASK_STATE FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
        FOR row_var IN task_cursor DO
            TASK_STATE := row_var.TASK_STATE;
        END FOR;
    EXCEPTION
        WHEN OTHER THEN
            TASK_STATE := 'UNKNOWN';
    END;

    TOTAL_RESULTS := :TOTAL_RESULTS || 'Current Task State: ' || :TASK_STATE || CHR(10);

    IF (UPPER(:TASK_STATE) = 'STARTED') THEN
        TASK_WAS_RUNNING := TRUE;

        SELECT COUNT(*) INTO :IS_EXECUTING
        FROM TABLE(DB_POC_HARMONIZED.INFORMATION_SCHEMA.TASK_HISTORY(
            TASK_NAME => 'TASK_POC_LOAD',
            RESULT_LIMIT => 5
        ))
        WHERE STATE = 'EXECUTING';

        WHILE (:IS_EXECUTING > 0) DO
            TOTAL_RESULTS := :TOTAL_RESULTS || 'Task currently executing, waiting 10s...' || CHR(10);
            CALL SYSTEM$WAIT(10, 'SECONDS');

            SELECT COUNT(*) INTO :IS_EXECUTING
            FROM TABLE(DB_POC_HARMONIZED.INFORMATION_SCHEMA.TASK_HISTORY(
                TASK_NAME => 'TASK_POC_LOAD',
                RESULT_LIMIT => 5
            ))
            WHERE STATE = 'EXECUTING';
        END WHILE;

        TOTAL_RESULTS := :TOTAL_RESULTS || 'Task execution completed. Suspending task...' || CHR(10);

        BEGIN
            EXECUTE IMMEDIATE 'ALTER TASK ' || :TASK_NAME || ' SUSPEND';
            TOTAL_RESULTS := :TOTAL_RESULTS || '[SUCCESS] Task Suspended successfully' || CHR(10) || CHR(10);
        EXCEPTION
            WHEN OTHER THEN
                TOTAL_RESULTS := :TOTAL_RESULTS || '[WARNING] Could not suspend task: ' || SQLERRM || CHR(10) || CHR(10);
        END;
    ELSE
        TOTAL_RESULTS := :TOTAL_RESULTS || 'Task is not running, no need to suspend' || CHR(10) || CHR(10);
    END IF;

    TOTAL_RESULTS := :TOTAL_RESULTS || '== CATCHUP PROCESSING ==' || CHR(10);

    SELECT COALESCE(MAX(LATEST_PROCESSING_DELAY_MINS), 0)
    INTO :CURRENT_DELAY_MINS
    FROM DB_POC_HARMONIZED.SCH_COMMON_UTILS.VW_PIPELINE_DELAY_MONITOR
    LIMIT 1;

    WHILE (:CURRENT_DELAY_MINS > :DELAY_THRESHOLD_MINS AND :CURRENT_ITERATION < :ITERATIONS_NEEDED) DO
        CURRENT_ITERATION := :CURRENT_ITERATION + 1;

        EXECUTE TASK DB_POC_HARMONIZED.SCH_COMMON_UTILS.TASK_POC_LOAD;

        WAIT_COUNTER := 0;
        IS_EXECUTING := 1;
        CALL SYSTEM$WAIT(3, 'SECONDS');

        WHILE (:IS_EXECUTING > 0 AND :WAIT_COUNTER < 30) DO
            SELECT COUNT(*) INTO :IS_EXECUTING
            FROM TABLE(DB_POC_HARMONIZED.INFORMATION_SCHEMA.TASK_HISTORY(
                TASK_NAME => 'TASK_POC_LOAD',
                RESULT_LIMIT => 1
            ))
            WHERE STATE = 'EXECUTING';

            IF (:IS_EXECUTING > 0) THEN
                CALL SYSTEM$WAIT(5, 'SECONDS');
                WAIT_COUNTER := :WAIT_COUNTER + 1;
            END IF;
        END WHILE;

        SELECT COALESCE(MAX(LATEST_PROCESSING_DELAY_MINS), 0)
        INTO :CURRENT_DELAY_MINS
        FROM DB_POC_HARMONIZED.SCH_COMMON_UTILS.VW_PIPELINE_DELAY_MONITOR
        LIMIT 1;

        TOTAL_RESULTS := :TOTAL_RESULTS || 'Iteration ' || :CURRENT_ITERATION || ' | Remaining Delay: ' || :CURRENT_DELAY_MINS || ' mins' || CHR(10);
    END WHILE;

    TOTAL_RESULTS := :TOTAL_RESULTS || CHR(10) || '== CATCHUP COMPLETED ==' || CHR(10);
    TOTAL_RESULTS := :TOTAL_RESULTS || 'Total Iterations: ' || :CURRENT_ITERATION || CHR(10);
    TOTAL_RESULTS := :TOTAL_RESULTS || 'Final Delay: ' || :CURRENT_DELAY_MINS || ' mins' || CHR(10);

    INSERT INTO DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
        (SOURCE, STATUS, ERROR_MESSAGE)
    VALUES (
        'CATCHUP_MONITOR',
        'CATCHUP_COMPLETED',
        'Processed ' || :CURRENT_ITERATION || ' catchup iterations. Final Delay: ' || :CURRENT_DELAY_MINS || ' mins'
    );

    TOTAL_RESULTS := :TOTAL_RESULTS || '== TASK RESUME ==' || CHR(10);

    IF (:TASK_WAS_RUNNING = TRUE OR :CURRENT_DELAY_MINS <= :DELAY_THRESHOLD_MINS) THEN
        TOTAL_RESULTS := :TOTAL_RESULTS || 'Delay within threshold (' || :DELAY_THRESHOLD_MINS || ' mins) - resuming task..' || CHR(10);
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TASK ' || :TASK_NAME || ' RESUME';
            TOTAL_RESULTS := :TOTAL_RESULTS || '[SUCCESS] Task resumed successfully' || CHR(10);
        EXCEPTION
            WHEN OTHER THEN
                TOTAL_RESULTS := :TOTAL_RESULTS || '[ERROR] Could not resume task: ' || SQLERRM || CHR(10);
        END;
    ELSE
        TOTAL_RESULTS := :TOTAL_RESULTS || 'Delay still exceeds threshold. Task remains suspended.' || CHR(10);
    END IF;

    RETURN :TOTAL_RESULTS;

EXCEPTION
    WHEN OTHER THEN
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TASK ' || :TASK_NAME || ' RESUME';
        EXCEPTION
            WHEN OTHER THEN
                NULL;
        END;
        RETURN 'CATCHUP FAILED AT ITERATION ' || :CURRENT_ITERATION || ': ' || SQLERRM;
END
$$;
