USE ROLE ROLE_POC_ADMIN;
USE WAREHOUSE WH_POC_XS;

--2.1CREATE DATABASE: 
CREATE DATABASE IF NOT EXISTS DB_POC_RAW;

CREATE DATABASE IF NOT EXISTS DB_POC_HARMONIZED;

--2.2. CREATE SCHEMAs
CREATE SCHEMA IF NOT EXISTS DB_POC_RAW.SCH_FAST;

CREATE SCHEMA IF NOT EXISTS DB_POC_HARMONIZED.SCH_COMMON_UTILS;

CREATE SCHEMA IF NOT EXISTS DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL;

--2.3 Grant Privileges to Engineer role

USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE DB_POC_RAW TO ROLE ROLE_POC_ENGINEER;

GRANT USAGE ON DATABASE DB_POC_HARMONIZED TO ROLE ROLE_POC_ENGINEER;


GRANT USAGE , CREATE TABLE , CREATE VIEW ON SCHEMA  DB_POC_RAW.SCH_FAST TO ROLE ROLE_POC_ENGINEER;

GRANT SELECT , INSERT , UPDATE , DELETE ON ALL TABLES IN SCHEMA DB_POC_RAW.SCH_FAST TO ROLE ROLE_POC_ENGINEER;
GRANT SELECT , INSERT , UPDATE , DELETE ON FUTURE TABLES IN SCHEMA DB_POC_RAW.SCH_FAST TO ROLE ROLE_POC_ENGINEER;

GRANT USAGE , CREATE TABLE , CREATE VIEW ON SCHEMA  DB_POC_HARMONIZED.SCH_COMMON_UTILS TO ROLE ROLE_POC_ENGINEER;
GRANT SELECT , INSERT , UPDATE , DELETE ON ALL TABLES IN SCHEMA DB_POC_HARMONIZED.SCH_COMMON_UTILS TO ROLE ROLE_POC_ENGINEER;
GRANT SELECT , INSERT , UPDATE , DELETE ON FUTURE TABLES IN SCHEMA DB_POC_HARMONIZED.SCH_COMMON_UTILS TO ROLE ROLE_POC_ENGINEER;


GRANT USAGE , CREATE TABLE , CREATE VIEW ON SCHEMA  DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL TO ROLE ROLE_POC_ENGINEER;
GRANT SELECT , INSERT , UPDATE , DELETE ON ALL TABLES IN SCHEMA DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL TO ROLE ROLE_POC_ENGINEER;
GRANT SELECT , INSERT , UPDATE , DELETE ON FUTURE TABLES IN SCHEMA DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL TO ROLE ROLE_POC_ENGINEER;


--Create Table
USE ROLE ROLE_POC_ENGINEER;

USE WAREHOUSE WH_POC_XS;

--3.1 Tracking Table creation

Create table if not exists DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING(
TRACKING_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
SOURCE VARCHAR(100),
STATUS VARCHAR(50),
PROCESS_TRACKING_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
DATA_START_TIMESTAMP_EPOCH FLOAT,
DATA_END_TIMESTAMP_EPOCH FLOAT,
ERROR_MESSAGE VARCHAR(1677216),
PRIMARY KEY(TRACKING_ID)
) COMMENT ='Tracks pipeline processing windows for catchup automation';

--3.2 Event_log creation
CREATE TABLE IF NOT EXISTS DB_POC_RAW.SCH_FAST.EVENT_LOG(
RECORD_CONTENT VARIANT,
RECORD_METADATA VARIANT,
_ETL_CREATE_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)COMMENT ='Raw event log table';


--3.3 TARGET DIMENSION TABLE CREATION 

--CREATE OR REPLACE TABLE DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL.TB_DIM_SAMPLE (
  SAMPLE_ID VARCHAR(50000),
  SAMPLE_NAME VARCHAR(50000),
  SAMPLE_STATUS VARCHAR(50000),
  SAMPLE_EMAIL VARCHAR(500000),
  ETL_CREATE_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ETL_UPDATE_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT ='USample dimension table';

--Create Incremental View 


select * from DB_POC_RAW.SCH_FAST.EVENT_LOG;

