USE ROLE ROLE_POC_ENGINEER;
USE WAREHOUSE WH_POC_XS;


select * from DB_POC_HARMONIZED.SCH_COMMON_UTILS.VW_PIPELINE_DELAY_MONITOR;

create or replace view DB_POC_HARMONIZED.SCH_COMMON_UTILS.VW_PIPELINE_DELAY_MONITOR(
	TRACKING_ID,
	SOURCE,
	STATUS,
	PROCESS_TRACKING_TIMESTAMP,
	DATA_START_TIMESTAMP_EPOCH,
	DATA_END_TIMESTAMP_EPOCH,
	DATA_START_TIMESTAMP,
	DATA_END_TIMESTAMP,
	LATEST_PROCESSING_DELAY_MINS,
	ACTUAL_DELAY_MINS,
	NEEDS_CATCHUP,
	CATCHUP_ITERATIONS_NEEDED
) COMMENT='Monitors Pipeline delay - triggers catchup when delay > 15 mins'
 as
SELECT 
   TRACKING_ID,
   SOURCE,
   STATUS,
   PROCESS_TRACKING_TIMESTAMP,
   DATA_START_TIMESTAMP_EPOCH,
   DATA_END_TIMESTAMP_EPOCH,
   TO_TIMESTAMP(DATA_START_TIMESTAMP_EPOCH::NUMBER / 1000) AS DATA_START_TIMESTAMP ,
   TO_TIMESTAMP(DATA_END_TIMESTAMP_EPOCH::NUMBER / 1000) AS DATA_END_TIMESTAMP,
   DATEDIFF('minute',PROCESS_TRACKING_TIMESTAMP , CURRENT_TIMESTAMP()) AS LATEST_PROCESSING_DELAY_MINS,
   ROUND(
         (DATE_PART(EPOCH_MILLISECOND, CURRENT_TIMESTAMP())- DATA_END_TIMESTAMP_EPOCH)/(1000 *60), 2
         ) AS ACTUAL_DELAY_MINS,
   CASE  
      WHEN DATEDIFF('minute',PROCESS_TRACKING_TIMESTAMP, CURRENT_TIMESTAMP())>15
      THEN TRUE
      ELSE FALSE 
  END AS NEEDS_CATCHUP,
  FLOOR(
  DATEDIFF('minute',PROCESS_TRACKING_TIMESTAMP,CURRENT_TIMESTAMP())/15
  ) AS CATCHUP_ITERATIONS_NEEDED
  FROM DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING where STATUS='COMPLETED' and SOURCE='POC_EVENTS'
  ORDER BY PROCESS_TRACKING_TIMESTAMP DESC;
