USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NOTIFICATION INTEGRATION POC_EMAIL_NOTIFICATION
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ('sample@gamil.com');

GRANT USAGE ON INTEGRATION POC_EMAIL_NOTIFICATION TO ROLE ROLE_POC_ENGINEER;
