USE ROLE ROLE_POC_ENGINEER;
USE WAREHOUSE WH_POC_XS;

CREATE OR REPLACE PROCEDURE DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL.SP_POC_LOAD_HARMONIZED("PARAM_INITIAL_DATA_EPOCH" FLOAT DEFAULT 0, "PARAM_DATA_PROCESSING_DURATION_EPOCH" FLOAT DEFAULT (CAST(15 * 60 AS NUMBER(4,0))) * 1000, "PARAM_TIME_BUFFER" FLOAT DEFAULT (CAST(15 * 60 AS NUMBER(4,0))) * 1000)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='POC Combined procedure processes events from raw to harmonized with inline SCD1'
EXECUTE AS CALLER
AS
$$
DECLARE
    DATA_START_TS_EPOCH FLOAT := -1;
    DATA_END_TS_EPOCH FLOAT := -1;
    CURRENT_STEP VARCHAR := 'Not Defined Yet';
    PROC_NAME VARCHAR := 'SP_POC_LOAD_HARMONIZED';
    LATEST_TRACKING_DATE FLOAT := -1;
    CNT_EVENT_LOG FLOAT := -1;
BEGIN
    CURRENT_STEP := 'TB_HARMONIZED_TRACKING - Finding Max Tracking Timestamp';

    SELECT COALESCE(MAX(DATA_END_TIMESTAMP_EPOCH), :PARAM_INITIAL_DATA_EPOCH)
    INTO :LATEST_TRACKING_DATE
    FROM DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
    WHERE STATUS = 'COMPLETED' AND SOURCE = 'POC_EVENTS';

    CURRENT_STEP := 'TB_HARMONIZED_TRACKING - Building Timeframe';

    SELECT
        :LATEST_TRACKING_DATE AS DATA_START_TS_EPOCH,
        LEAST(
            (:LATEST_TRACKING_DATE + :PARAM_DATA_PROCESSING_DURATION_EPOCH),
            (DATE_PART(EPOCH_MILLISECOND, CURRENT_TIMESTAMP()) - :PARAM_TIME_BUFFER)
        ) AS DATA_END_TS_EPOCH
    INTO :DATA_START_TS_EPOCH, :DATA_END_TS_EPOCH;

    CURRENT_STEP := 'TB_HARMONIZED_TRACKING - STARTED';

    INSERT INTO DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
        (SOURCE, PROCESS_TRACKING_TIMESTAMP, DATA_START_TIMESTAMP_EPOCH, DATA_END_TIMESTAMP_EPOCH, STATUS)
    VALUES
        ('POC_EVENTS', CURRENT_TIMESTAMP(), :DATA_START_TS_EPOCH, :DATA_END_TS_EPOCH, 'STARTED');

    CURRENT_STEP := 'Counting events in window';

    SELECT COUNT(1) INTO :CNT_EVENT_LOG
    FROM DB_POC_RAW.SCH_FAST.EVENT_LOG
    WHERE RECORD_CONTENT:Event IN ('SampleInsert', 'SampleUpdate')
        AND RECORD_METADATA:SnowflakeConnectorPushTime > :DATA_START_TS_EPOCH
        AND RECORD_METADATA:SnowflakeConnectorPushTime <= :DATA_END_TS_EPOCH;

    IF (:CNT_EVENT_LOG > 0) THEN
        CURRENT_STEP := 'TB_DIM_SAMPLE - VW_POC_SAMPLE_INSERT - SCD1 MERGE';

        MERGE INTO DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL.TB_DIM_SAMPLE tgt
        USING DB_POC_RAW.SCH_FAST.VW_POC_SAMPLE_INSERT src
        ON tgt.SAMPLE_ID = src.SAMPLE_ID
        WHEN MATCHED AND tgt._ROW_HASH != src._ROW_HASH THEN
            UPDATE SET
                tgt.SAMPLE_NAME = src.SAMPLE_NAME,
                tgt.SAMPLE_STATUS = src.SAMPLE_STATUS,
                tgt.SAMPLE_EMAIL = src.SAMPLE_EMAIL,
                tgt._ROW_HASH = src._ROW_HASH,
                tgt._ETL_UPDATE_TS = CURRENT_TIMESTAMP(),
                tgt.SRC_EVENT_CREATE_TIME = src.SRC_EVENT_CREATE_TIME
        WHEN NOT MATCHED THEN
            INSERT (SAMPLE_ID, SAMPLE_NAME, SAMPLE_STATUS, SAMPLE_EMAIL, _ROW_HASH,
                    _ETL_CREATE_TS, _ETL_UPDATE_TS, SRC_EVENT_CREATE_TIME, DELETE_FLAG)
            VALUES (src.SAMPLE_ID, src.SAMPLE_NAME, src.SAMPLE_STATUS, src.SAMPLE_EMAIL,
                    src._ROW_HASH, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.SRC_EVENT_CREATE_TIME, FALSE);

        CURRENT_STEP := 'TB_HARMONIZED_TRACKING - COMPLETED - Processed New Data';

        INSERT INTO DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
            (SOURCE, PROCESS_TRACKING_TIMESTAMP, DATA_START_TIMESTAMP_EPOCH, DATA_END_TIMESTAMP_EPOCH, STATUS)
        VALUES
            ('POC_EVENTS', CURRENT_TIMESTAMP(), :DATA_START_TS_EPOCH, :DATA_END_TS_EPOCH, 'COMPLETED');

        RETURN 'COMPLETED - Processed ' || :CNT_EVENT_LOG || ' events: ' || :DATA_START_TS_EPOCH || ' to ' || :DATA_END_TS_EPOCH;

    ELSE
        CURRENT_STEP := 'TB_HARMONIZED_TRACKING - COMPLETED - No New Data';

        INSERT INTO DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
            (SOURCE, PROCESS_TRACKING_TIMESTAMP, DATA_START_TIMESTAMP_EPOCH, DATA_END_TIMESTAMP_EPOCH, STATUS)
        VALUES
            ('POC_EVENTS', CURRENT_TIMESTAMP(), :DATA_START_TS_EPOCH, :DATA_END_TS_EPOCH, 'COMPLETED');

        RETURN 'COMPLETED - No New Data: ' || :DATA_START_TS_EPOCH || ' to ' || :DATA_END_TS_EPOCH;
    END IF;

EXCEPTION
    WHEN OTHER THEN
        INSERT INTO DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
            (SOURCE, PROCESS_TRACKING_TIMESTAMP, DATA_START_TIMESTAMP_EPOCH, DATA_END_TIMESTAMP_EPOCH, STATUS, ERROR_MESSAGE)
        VALUES
            ('POC_EVENTS', CURRENT_TIMESTAMP(), :DATA_START_TS_EPOCH, :DATA_END_TS_EPOCH, 'FAILED', SQLERRM);

        RETURN 'FAILED at ' || :CURRENT_STEP || ': ' || SQLERRM;
END
$$;
