--1.1CREATE ROLES
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ROLE_POC_ADMIN;

CREATE ROLE IF NOT EXISTS ROLE_POC_ENGINEER;

--BUILD LOAD HIRARCHY
GRANT ROLE ROLE_POC_ENGINEER TO ROLE ROLE_POC_ADMIN;

GRANT ROLE ROLE_POC_ADMIN TO ROLE ACCOUNTADMIN;

--1.2 -Create Warehouse
Create WAREHOUSE IF NOT EXISTS WH_POC_XS;

--GRANT WAREHOUSE ACCESS 
GRANT USAGE, OPERATE ON WAREHOUSE  WH_POC_XS TO ROLE ROLE_POC_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE  WH_POC_XS TO ROLE ROLE_POC_ENGINEER;

--1.3 GRANT ACCOUNT LEVEL PRIVILEGE

GRANT CREATE DATABASE ON ACCOUNT TO ROLE ROLE_POC_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_POC_ENGINEER;

--ASSIGN ROLE TO YOUR USER
GRANT ROLE ROLE_POC_ADMIN TO USER SWETHA;
GRANT ROLE ROLE_POC_ENGINEER TO USER SWETHA;

--set defualt role
ALTER USER SWETHA SET DEFUALT_ROLE = ROLE_POC_ENGINEER;
