CREATE OR REPLACE TASK DB_POC_HARMONIZED.SCH_COMMON_UTILS.TASK_POC_LOAD
  WAREHOUSE = WH_POC_XS
  SCHEDULE = 'USING CRON 0 */15 * * * UTC'
  COMMENT = 'Runs harmonized load every 15 minutes'
AS
  CALL DB_POC_HARMONIZED.SCH_COMMON_DATA_MODEL.SP_POC_LOAD_HARMONIZED();


USE ROLE SECURITYADMIN;
GRANT CREATE TASK ON SCHEMA DB_POC_HARMONIZED.SCH_COMMON_UTILS TO ROLE ROLE_POC_ENGINEER;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_POC_ENGINEER;


create or replace task DB_POC_HARMONIZED.SCH_COMMON_UTILS.TASK_POC_CATCHUP_MONITOR
	warehouse=WH_POC_XS
	schedule='USING CRON */5 * * * * UTC'
	COMMENT='Monitoring task: Checks delay every 5 minutes - only triggers catchup if delay > 15 mins'
	as DECLARE
    DELAY_MINS NUMBER := 0;
    NEEDS_CATCHUP BOOLEAN := FALSE;
    CATCHUP_RESULT STRING := '';
BEGIN
    SELECT
        COALESCE(LATEST_PROCESSING_DELAY_MINS, 0),
        COALESCE(NEEDS_CATCHUP, FALSE)
    INTO :DELAY_MINS, :NEEDS_CATCHUP
    FROM DB_POC_HARMONIZED.SCH_COMMON_UTILS.VW_PIPELINE_DELAY_MONITOR
    ORDER BY TRACKING_ID DESC
    LIMIT 1;

    IF (:DELAY_MINS <= 15) THEN
        RETURN;
    END IF;

    IF (:NEEDS_CATCHUP = TRUE AND :DELAY_MINS > 15) THEN
        CALL DB_POC_HARMONIZED.SCH_COMMON_UTILS.SP_CATCHUP_PROCESSOR(50, 15) INTO :CATCHUP_RESULT;

        INSERT INTO DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
            (SOURCE, STATUS, ERROR_MESSAGE)
        VALUES (
            'CATCHUP_MONITOR',
            'CATCHUP_TRIGGERED',
            :CATCHUP_RESULT
        );
    END IF;
END;
