
USE ROLE ROLE_POC_ENGINEER;
USE WAREHOUSE WH_POC_XS;



CREATE OR REPLACE VIEW DB_POC_RAW.SCH_FAST.VW_POC_SAMPLE_INSERT
COMMENT = 'Incremental view - reads SampleInsert events within current processing window'
AS
WITH tracking AS (
    SELECT
        MAX(DATA_START_TIMESTAMP_EPOCH) AS DATA_START_TIMESTAMP_MAX,
        MAX(DATA_END_TIMESTAMP_EPOCH) AS DATA_END_TIMESTAMP_MAX
    FROM DB_POC_HARMONIZED.SCH_COMMON_UTILS.TB_HARMONIZED_TRACKING
    WHERE STATUS = 'STARTED' AND SOURCE = 'POC_EVENTS'
)
SELECT
    RECORD_CONTENT:id::VARCHAR AS SAMPLE_ID,
    RECORD_CONTENT:name::VARCHAR AS SAMPLE_NAME,
    RECORD_CONTENT:status::VARCHAR AS SAMPLE_STATUS,
    RECORD_CONTENT:email::VARCHAR AS SAMPLE_EMAIL,
    RECORD_METADATA:SnowflakeConnectorPushTime::FLOAT AS SRC_EVENT_CREATE_TIME,
    MD5(
        COALESCE(RECORD_CONTENT:id::VARCHAR, '') || '|' ||
        COALESCE(RECORD_CONTENT:name::VARCHAR, '') || '|' ||
        COALESCE(RECORD_CONTENT:status::VARCHAR, '') || '|' ||
        COALESCE(RECORD_CONTENT:email::VARCHAR, '')
    ) AS _ROW_HASH
FROM DB_POC_RAW.SCH_FAST.EVENT_LOG e, tracking t
WHERE RECORD_CONTENT:Event::VARCHAR = 'SampleInsert'
    AND RECORD_METADATA:SnowflakeConnectorPushTime > t.DATA_START_TIMESTAMP_MAX
    AND RECORD_METADATA:SnowflakeConnectorPushTime <= t.DATA_END_TIMESTAMP_MAX;
